### ISSUE TITLE
first

### ISSUE THREAD

**Issue by CelesteBlue-dev** [SilicaAndPina/Package-Installer-Enabler#1]
nothing to say
except : good job !
If you want to continue coding in C, ask me, I will help you.

Please share the full src code, the one of the .bin.
Move the current github files to a folder called Release.
Like that : https://github.com/Joonie86/Rebug-Toolbox

I will upload VitaRW_for_LUA src code on my github.
All the best

**Comment by SilicaAndPina** [comment]
this isnt an issue..
