### ISSUE TITLE
Can't change PKG Installer

### ISSUE THREAD

**Issue by metal-velcro** [SilicaAndPina/Package-Installer-Enabler#2]
Ok so I installed DEX PKG installer on my PSTV. I wanted to try CEX MOD but the VPK fails upon install and the bubble is gone from the Live area. Any ideas short of using VitaRW and FTP over the files?

**Comment by SilicaAndPina** [comment]
Rebuild database... or psgm:play?titleid=PKGE00001

i should probably make this easier..

**Comment by CelesteBlue-dev** [comment]
It works being connected to QCMA with WIFI.

**Comment by SilicaAndPina** [comment]
wow celeste! i did not know that!
